repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: infracost_breakdown
      args:
        - --args=--path=./
      verbose = true
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.16 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"
    - id: terraform-validate

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-system
      args: ["markdown", "--output-file", "README.md", "./"]
- repo: git://github.com/smian/pre-commit-makefile
  sha: master
  hooks:
    - id: makefile-doc
